"""Add the table of pharmacies

Revision ID: 6ef38f4b27a2
Revises: 
Create Date: 2019-08-26 07:58:19.277623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef38f4b27a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_name', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('zip', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.String(length=64), nullable=True),
    sa.Column('longitude', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_address'), 'pharmacy', ['address'], unique=True)
    op.create_index(op.f('ix_pharmacy_latitude'), 'pharmacy', ['latitude'], unique=False)
    op.create_index(op.f('ix_pharmacy_longitude'), 'pharmacy', ['longitude'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pharmacy_longitude'), table_name='pharmacy')
    op.drop_index(op.f('ix_pharmacy_latitude'), table_name='pharmacy')
    op.drop_index(op.f('ix_pharmacy_address'), table_name='pharmacy')
    op.drop_table('pharmacy')
    # ### end Alembic commands ###
